/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { GalaxyWarContract } from "./GalaxyWar";
import { MigrationsContract } from "./Migrations";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "GalaxyWar"): GalaxyWarContract;
      require(name: "Migrations"): MigrationsContract;
    }
  }
}

export { GalaxyWarContract, GalaxyWarInstance } from "./GalaxyWar";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
